version: "3.9"

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: task2-jenkins
    ports:
      - "8081:8080"
    volumes:
      - jenkins_home_task2:/var/jenkins_home
      - ./:/workspace
      # Intentionally insecure: docker.sock mount -> host takeover risk
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  app:
    build:
      context: ../app
      dockerfile: Dockerfile
    container_name: task2-app
    ports:
      - "3000:8000"
    # Intentionally insecure runtime config for misconfig findings:
    privileged: true
    restart: unless-stopped

volumes:
  jenkins_home_task2:
